name: mindline
services:
  - name: web
    source_dir: /
    github:
      repo: LiamF-1/mind-line
      branch: deployment-setup
      deploy_on_push: true
    build_command: pnpm install --frozen-lockfile && cd apps/web && pnpm exec prisma generate && cd ../.. && pnpm build
    run_command: pnpm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_URL
        value: ${mindline_db.DATABASE_URL}

      - key: NEXTAUTH_URL
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}

databases:
  - name: mindline-db
    engine: PG
    version: '15'
    production: false
