name: mindline
services:
  - name: web
    source_dir: /
    github:
      repo: LiamF-1/mind-line
      branch: main
      deploy_on_push: true
    build_command: pnpm install --frozen-lockfile && pnpm db:generate && pnpm build
    run_command: pnpm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    env:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_URL
        value: ${mindline-db.DATABASE_URL}
      - key: REDIS_URL
        value: ${mindline-valkey.REDIS_URL}
      - key: NEXTAUTH_URL
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        value: rSR4lUcn04P7QLhSip/CUzu4XzQKXoeeL8WVUn/KmmI=

databases:
  - name: mindline-db
    engine: PG
    version: '15'
    size: basic

  - name: mindline-valkey
    engine: VALKEY
    version: '7'
    size: basic
