name: mindline
services:
  - name: web
    source_dir: /
    github:
      repo: LiamF-1/mind-line
      branch: main
      deploy_on_push: true
    build_command: pnpm install --frozen-lockfile && pnpm db:generate && pnpm build
    run_command: pnpm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_URL
        value: ${POSTGRES_DATABASE_URL}
      - key: REDIS_URL
        value: ${REDIS_DATABASE_URL}
      - key: NEXTAUTH_URL
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
# Using existing databases - no need to create new ones
